### PR TITLE
Add 'Move to...' and 'Copy to...' feature

### PR DESCRIPTION
**Pull request by trandaison**
Related issue: https://github.com/trandaison/vscode-duplicate/issues/1

Add `Move to...` and `Copy to...` command to right context menu on explorer bar.

Screenshot 2023-10-23 at 10 45 36

### CODE REVIEW

**Comment by ghost** [comment]
I can't copy to../move to.. folders to another location on Windows 10. There's a bug somewhere.

Sorry, I didn't check back earlier.

**Comment by trandaison** [comment]
@backermanbd That's bad. I don't have a Windows 10 to debug.

I already handle the error while perform a move/copy https://github.com/trandaison/vscode-duplicate/pull/3/files#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R43, it should display an error message, is there any message?

However, I the `rename` function and `copy` function that I am using in this extension are from the built-in api of vscode, not from nodejs itself. If there is any problem, it could be from the vscode.

May be you don't have permission or vscode don't have permission to move/copy file to that directory, I guess 🤔

**Comment by ghost** [comment]
No, vscode doesn't show any error message.

This dialog box opens up when I try to copy/move a folder.
When moving a folder, the dialog is identical to moving a file but remains empty.

Here's when I try to copy a folder to another location.

Capture

**Comment by ghost** [comment]
I will settle now as this doesn't work on Windows: duplicate the file/directory and move it manually to the target location.

Issue https://github.com/trandaison/vscode-duplicate/issues/6

**Comment by ghost** [comment]
Alternative: Windows users can use `v0.0.2` as it doesn't have `Move to...` and `Copy to...` feature.

**Pull request merged**
